# Generated by Django 2.1.5 on 2019-01-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_count',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
