# Generated by Django 2.1.5 on 2019-01-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
